### ISSUE TITLE
arrow.parser.ParserError

### ISSUE THREAD

**Issue by EvangMM** [CristianCantoro/wikipedia-graphsnapshot#1]
### Testing enviroment
virtualenviroment python 3.6.7 with dependencies for wikidump and graphsnapshot

When I run:
  

`python3 -m wikidump "path"/enwiki-20200401-pages-meta-history27.xml-p63353171p63542866.7z "output_path" extract-wikilinks`

the result, after the processing, is a rawlink dataset:
<p>"enwiki-20200401-pages-meta-history27.xml-p63353171p63542866.7z.features.xml"</p>

then:
`python3 -m graphsnapshot "rawlink dataset" "output_path" extract-snapshot`

but I get this error:
`Analyzing ../data/3a-redirects/enwiki-20200401-pages-meta-history27.xml-p63353171p63542866.7z.features.xml...Traceback (most recent call last):
    File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
    File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
    File "/home/mmartini/pyproj/testwiki/wiki/repository/graphsnapshot/graphsnapshot/__main__.py", line 85, in <module>
        main()
    File "/home/mmartini/pyproj/testwiki/wiki/repository/graphsnapshot/graphsnapshot/__main__.py", line 75, in main
        args,
    File "/home/mmartini/pyproj/testwiki/wiki/repository/graphsnapshot/graphsnapshot/processors/snapshot_extractor.py", line 485, in main
        for page, ts in pages_generator:
    File "/home/mmartini/pyproj/testwiki/wiki/repository/graphsnapshot/graphsnapshot/processors/snapshot_extractor.py", line 216, in process_lines
        arrow.get(revision_data['revision_timestamp'])
    File "/home/mmartini/.virtualenvs/testwiki/lib/python3.6/site-packages/arrow/api.py", line 22, in get
        return _factory.get(*args, **kwargs)
    File "/home/mmartini/.virtualenvs/testwiki/lib/python3.6/site-packages/arrow/factory.py", line 174, in get
        dt = parser.DateTimeParser(locale).parse_iso(arg)
    File "/home/mmartini/.virtualenvs/testwiki/lib/python3.6/site-packages/arrow/parser.py", line 119, in parse_iso
        return self._parse_multiformat(string, formats)
    File "/home/mmartini/.virtualenvs/testwiki/lib/python3.6/site-packages/arrow/parser.py", line 286, in _parse_multiformat
        raise ParserError('Could not match input to any of {} on \'{}\''.format(formats, string))
    arrow.parser.ParserError: Could not match input to any of ['YYYY-MM-DD', 'YYYY/MM/DD', 'YYYY.MM.DD', 'YYYY-MM', 'YYYY/MM', 'YYYY.MM', 'YYYY', 'YYYY', 'YYYY'] on 'revision_timestamp'`

**Comment by CristianCantoro** [comment]
The error is the following:
```
Could not match input to any of ['YYYY-MM-DD', 'YYYY/MM/DD', 'YYYY.MM.DD', 'YYYY-MM',
'YYYY/MM', 'YYYY.MM', 'YYYY', 'YYYY', 'YYYY'] on 'revision_timestamp'
```

the script expects that the input file name includes a date in one of the formats indicated if this is not the case you will get the error above.
